sudo: true

env:
  global:
  - SAUCE_USERNAME=sauce_examples

jobs:
  include:
    - stage: "Java tests"
      jdk: "openjdk8"
      before_install: export | grep SAUCE_
      script: make java_tests
    - stage "Python tests"
      python: "3.6"
      script: make python_tests
    - stage "Ruby tests"
      rvm: "2.5.3"
      script: make ruby_tests
