sudo: true

env:
  global:
  - SAUCE_USERNAME=sauce_examples

jobs:
  include:
    - stage: "Run All Tests"
      python: "3.6"
      jdk: "openjdk8"
      rvm: "2.5.3"
      before_install: export | grep SAUCE_
      script: make java_tests
      script: make python_tests
      script: make ruby_tests
